// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: batch.go

package db

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const linkPerformers = `-- name: LinkPerformers :batchexec
insert into event_performers (event_id, performer_id)
select $1, performers.id
from performers
where name = $2
`

type LinkPerformersBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type LinkPerformersParams struct {
	EventID int32
	Name    string
}

func (q *Queries) LinkPerformers(ctx context.Context, arg []LinkPerformersParams) *LinkPerformersBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.EventID,
			a.Name,
		}
		batch.Queue(linkPerformers, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &LinkPerformersBatchResults{br, len(arg), false}
}

func (b *LinkPerformersBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *LinkPerformersBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const writePerformers = `-- name: WritePerformers :batchexec
insert into performers (name) values ($1)
on conflict (name) do nothing
`

type WritePerformersBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

func (q *Queries) WritePerformers(ctx context.Context, name []string) *WritePerformersBatchResults {
	batch := &pgx.Batch{}
	for _, a := range name {
		vals := []interface{}{
			a,
		}
		batch.Queue(writePerformers, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &WritePerformersBatchResults{br, len(name), false}
}

func (b *WritePerformersBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *WritePerformersBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
