// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateEvent(ctx context.Context, arg CreateEventParams) (int32, error)
	CreateVenue(ctx context.Context, arg CreateVenueParams) (int32, error)
	DeleteEvent(ctx context.Context, eventID int32) (int64, error)
	DeleteVenue(ctx context.Context, venueID int32) (int64, error)
	GetAvailableTickets(ctx context.Context, eventID int32) ([]GetAvailableTicketsRow, error)
	GetEvent(ctx context.Context, eventID int32) ([]GetEventRow, error)
	GetTicket(ctx context.Context, ticketID int32) (GetTicketRow, error)
	GetVenue(ctx context.Context, venueID int32) (GetVenueRow, error)
	LinkPerformers(ctx context.Context, arg []LinkPerformersParams) *LinkPerformersBatchResults
	LinkUpdatedPerformers(ctx context.Context, arg LinkUpdatedPerformersParams) error
	SetTicketPurchaser(ctx context.Context, arg SetTicketPurchaserParams) (int32, error)
	TrimUpdatedEventPerformers(ctx context.Context, eventID int32) error
	// The updated record's id is returned so that the generated query will return
	// an error (`sql.ErrNoRows`) if no record matches the where clause and no
	// record is updated.
	UpdateEvent(ctx context.Context, arg UpdateEventParams) (int32, error)
	// The updated record's id is returned so that the generated query will return
	// an error (`sql.ErrNoRows`) if no record matches the where clause and no
	// record is updated.
	UpdateVenue(ctx context.Context, arg UpdateVenueParams) (int32, error)
	// The inserted record's id is returned so that the generated query will return
	// an error (`sql.ErrNoRows`) if no record is inserted due to the where clause
	// not finding a matching event.
	WriteNewTickets(ctx context.Context, arg []WriteNewTicketsParams) *WriteNewTicketsBatchResults
	WritePerformers(ctx context.Context, name []string) *WritePerformersBatchResults
}

var _ Querier = (*Queries)(nil)
