// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateVenue(ctx context.Context, arg CreateVenueParams) (int32, error)
	DeleteVenue(ctx context.Context, venueID int32) (int64, error)
	GetVenue(ctx context.Context, venueID int32) (GetVenueRow, error)
	UpdateVenue(ctx context.Context, arg UpdateVenueParams) (int32, error)
}

var _ Querier = (*Queries)(nil)
