services:
  db:
    image: postgres:16.1-alpine
    env_file: .env
    ports:
      - "8432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

  dbmigrations:
    image: amacneil/dbmate:2
    env_file: .env
    volumes:
      - ./db:/db
    depends_on:
      - db

  cache:
    image: redis:7.4.1-bookworm
    ports:
      - "8379:6379"
    command: redis-server --save 60 1 --loglevel warning --requirepass app_user

  app:
    build: .
    env_file: .env
    ports:
      - "8000:${PORT}"
    depends_on:
      - cache
      - db

volumes:
  pg-data:
